# Generated by Django 5.2.3 on 2025-07-02 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='clave',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
